export enum GA_EVENTS {
  AUTO_CHECK = 'auto_check',
  AUTO_UNCHECK = 'auto_uncheck',
  CLEAR = 'clear',
  COMMAND = 'command',
  CONVERT = 'convert',
  CONVERT_AUTO = 'convert_auto',
  COPY_INPUT = 'copy_input',
  COPY_RESULT = 'copy_result',
  DASHBOARD = 'dashboard',
  DOWNLOAD = 'download',
  FAV_ADD = 'favorite_add',
  FAV_REMOVE = 'favorite_remove',
  GENERATE = 'generate',
  MINIFY = 'minify',
  PAGE_VIEW = 'page_view',
  PRETTY = 'pretty',
  RESET = 'reset',
  SAMPLE = 'sample',
  SEARCH = 'search',
  SIDEBAR_TOGGLE = 'sidebar_toggle',
  SWAP = 'swap',
  THEME_TOGGLE = 'theme_toggle',
  UPLOAD = 'upload',
}
