export enum ROUTES {
  HOME = '/',
  DASHBOARD = '/dashboard',
  PRIVACY = '/privacy',
  NUMBER_CONVERTER = '/number-converter',
  CASE_CONVERTER = '/case-converter',
  DATA_FORMAT_CONVERTER = '/data-format-converter',
  ENCODER_DECODER = '/encoder-decoder',
  HASH_GENERATOR = '/hash-generator',
  JWT_DECODER = '/jwt-decoder',
  LOREM_GENERATOR = '/lorem-generator',
  ID_GENERATOR = '/id-generator',
  LENGTH_CONVERTER = '/unit-converter/length',
  AREA_CONVERTER = '/unit-converter/area',
  VOLUME_CONVERTER = '/unit-converter/volume',
  WEIGHT_CONVERTER = '/unit-converter/weight',
  TEMPERATURE_CONVERTER = '/unit-converter/temperature',
  TIME_CONVERTER = '/unit-converter/time',
  SPEED_CONVERTER = '/unit-converter/speed',
  DATA_SIZE_CONVERTER = '/unit-converter/data-size',
  COLOR_PICKER = '/color-picker',
}
