export enum ROUTES {
  HOME = '/',
  DASHBOARD = '/dashboard',
  PRIVACY = '/privacy',
  NUMBER_CONVERTER = '/number-converter',
  CASE_CONVERTER = '/case-converter',
  DATA_FORMAT_CONVERTER = '/data-format-converter',
  ENCODER_DECODER = '/encoder-decoder',
  HASH_GENERATOR = '/hash-generator',
  JWT_DECODER = '/jwt-decoder',
  LOREM_GENERATOR = '/lorem-generator',
  ID_GENERATOR = '/id-generator',
  LENGTH_CONVERTER = '/unit-converter/length',
  WEIGHT_CONVERTER = '/unit-converter/weight',
  VOLUME_CONVERTER = '/unit-converter/volume',
}
